package app.accounting.accounts;

public enum AccountType {

    ASSETS("ASSETS"),
    //CURRENT_ASSET(CASH,BANK,INVENTORY,ACC_RECEIVABLE,VAT_RECEIVABLE,INTEREST_RECEIVABLE),
    //FIXED_ASSET(FURNITURE,VEHICLE,PERSONAL_ASSET)
    LIABILITIES("LIABILITIES"),
    //ACC_PAYABLE,LOAN_PAYABLE,SALARY_PAYABLE,VAT_OUTPUT
    EQUITY("EQUITY"),
    //WITHDRAWAL,OWNERS_CAPITAL,RETAINED_EARNINGS(REVENUE-EXPENSE)
    INCOME("INCOME"),
    //SALES_REVENUE,SALES_RETURN,DISCOUNT_REVENUE,DISCOUNT_RECEIVED,BANK_INTEREST
    EXPENSE("EXPENSE") ;
    //COGS,RENT,LOAN_INTEREST_EXPENSE,SALARIES,OFFICE_SUPPLY,DEPRECIATION,UTILITIES,DISCOUNT_GIVEN

    private final String type;

    AccountType(String type){
        this.type=type;
    }
    public String getType(){
        return this.type;
    }

}
